# Generated by Django 4.2.16 on 2025-07-26 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_application', models.CharField(max_length=100)),
                ('perimetre', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('reference_demande', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date_ouverture', models.DateTimeField()),
                ('date_fermeture', models.DateTimeField(blank=True, null=True)),
                ('categorie', models.CharField(max_length=100)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('orientation', models.CharField(choices=[('refus', 'Refus'), ('non', 'Non orienté')], max_length=10)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='Chatbot.application')),
            ],
        ),
        migrations.CreateModel(
            name='Historique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requete', models.TextField()),
                ('reponse', models.TextField(blank=True, null=True)),
                ('date_requete', models.DateTimeField(auto_now_add=True)),
                ('conversation_id', models.CharField(help_text="Permet de relier les requêtes d'une même conversation", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('identifiant', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transfert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_transfert', models.DateTimeField()),
                ('identifiant_expert', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferts_expert', to='Chatbot.responsable')),
                ('identifiant_support', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferts_support', to='Chatbot.responsable')),
                ('ref_demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferts', to='Chatbot.demande')),
            ],
        ),
        migrations.CreateModel(
            name='Satisfaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('ref_demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satisfactions', to='Chatbot.demande')),
            ],
        ),
        migrations.AddField(
            model_name='demande',
            name='identifiant_demandeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes', to='Chatbot.responsable'),
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultat_audit', models.IntegerField()),
                ('date_audit', models.DateTimeField()),
                ('identifiant_audit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits_realises', to='Chatbot.responsable')),
                ('identifiant_demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='Chatbot.demande')),
            ],
        ),
    ]
