# Generated by Django 4.2.16 on 2025-08-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CasDeTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projet', models.CharField(max_length=100)),
                ('marco_scenario', models.CharField(max_length=200)),
                ('test_perimeter', models.CharField(max_length=100)),
                ('pre_requisites', models.TextField(blank=True, null=True)),
                ('profile', models.CharField(max_length=100)),
                ('test_cases', models.TextField()),
                ('prio', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10)),
                ('criticality', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=10)),
                ('test_state', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Blocked', 'Blocked'), ('KO', 'KO'), ('KO JDD', 'KO JDD'), ('OK', 'OK'), ('N/A', 'N/A')], max_length=20)),
                ('step_test', models.TextField()),
                ('expected_result', models.TextField()),
            ],
        ),
    ]
